name: nettrace
description: NetTrace - iOS 轻量本地 HTTP/HTTPS 抓包调试工具
publish_to: 'none'
version: 1.4.0+7

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # 加密 & 证书 (pointycastle 直接构造 X.509)
  pointycastle: ^4.0.0
  # 工具
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  # 后台保活（播放无声音频保持后台运行）
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/certs/
    - assets/audio/
